# Generated by Django 4.2.4 on 2023-09-25 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='project_fk',
        ),
        migrations.AddField(
            model_name='project',
            name='group_fk',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='springboard_api.group'),
        ),
    ]
