# Generated by Django 4.2.4 on 2023-09-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0002_remove_group_project_fk_project_group_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectboard',
            name='boardtype',
        ),
        migrations.AddField(
            model_name='projectboard',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
