# Generated by Django 4.2.5 on 2023-09-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0003_remove_projectboard_boardtype_projectboard_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboard',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
