# Generated by Django 4.2.4 on 2023-09-28 13:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0004_alter_projectboard_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('rules', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(default='0000-00-00 00:00:00')),
                ('teacher_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='springboard_api.teacher')),
            ],
        ),
    ]
