# Generated by Django 4.2.4 on 2023-10-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0005_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboard',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectboard',
            name='recommendation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectboard',
            name='references',
            field=models.TextField(default=''),
        ),
    ]
