# Generated by Django 4.2.4 on 2023-10-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0006_projectboard_feedback_projectboard_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
