# Generated by Django 4.2.4 on 2023-10-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0009_teacher_last_login_alter_teacher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
