# Generated by Django 4.2.4 on 2023-10-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0010_template_ispublic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboard',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
