# Generated by Django 4.2.4 on 2023-10-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0012_alter_template_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
