# Generated by Django 4.2.4 on 2023-10-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0013_project_ispublic_project_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
