# Generated by Django 4.2.4 on 2023-11-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0014_alter_project_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='isPublic',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='template',
            old_name='isPublic',
            new_name='isActive',
        ),
    ]
