# Generated by Django 4.2.4 on 2023-11-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0017_remove_template_teacher_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reason',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectboard',
            name='templateId',
            field=models.IntegerField(default=0),
        ),
    ]
