# Generated by Django 4.2.4 on 2023-11-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0018_project_reason_projectboard_templateid'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboard',
            name='boardId',
            field=models.IntegerField(default=0),
        ),
    ]
