# Generated by Django 4.2.4 on 2023-12-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0022_alter_admin_deleted_at_alter_student_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='key_code',
            field=models.CharField(default='', editable=False, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
