# Generated by Django 4.2.4 on 2023-12-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0023_group_key_code_alter_group_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
