# Generated by Django 4.2.4 on 2024-02-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0024_alter_classroom_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectboard',
            old_name='novelty',
            new_name='desirability',
        ),
        migrations.RenameField(
            model_name='projectboard',
            old_name='technical_feasibility',
            new_name='feasibility',
        ),
        migrations.RenameField(
            model_name='projectboard',
            old_name='capability',
            new_name='viability',
        ),
    ]
