# Generated by Django 4.2.4 on 2024-05-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0025_rename_novelty_projectboard_desirability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='exp_output',
            field=models.TextField(default=''),
        ),
    ]
