# Generated by Django 4.2.4 on 2024-05-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0026_template_exp_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboard',
            name='desirability',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='feasibility',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projectboard',
            name='viability',
            field=models.FloatField(),
        ),
    ]
