# Generated by Django 4.2.4 on 2024-05-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springboard_api', '0027_alter_projectboard_desirability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectboard',
            name='output_metric',
            field=models.FloatField(default=0),
        ),
    ]
